# Generated by Django 4.2.6 on 2023-10-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ApiDrinkSaver", "0002_remove_customuser_username_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False, verbose_name="Adresse e-mail vérifiée"
            ),
        ),
    ]
