# Generated by Django 4.2.6 on 2023-10-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ApiDrinkSaver", "0005_apikey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="", max_length=30, unique=True, verbose_name="Nom d'utilisateur"
            ),
        ),
    ]
