# Generated by Django 4.2.6 on 2023-10-30 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0005_emailaddress_idx_upper_email"),
        ("ApiDrinkSaver", "0006_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomEmailAddress",
            fields=[
                (
                    "emailaddress_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.emailaddress",
                    ),
                ),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("account.emailaddress",),
        ),
    ]
