# Generated by Django 4.2.6 on 2023-10-30 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ApiDrinkSaver", "0007_customemailaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customemailaddress",
            name="custom_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
